### ISSUE TITLE
[Feat] Support raw strings in Embed.footer

### ISSUE THREAD

**Issue by Wolfhound905** [NAFTeam/NAFF#428]
**Describe the bug**
When you set the footer in the embed class you get an erorr.

**To Reproduce**
The code you used to produce this bug, must be in a code-block:
```py
@dis.message_command("embed")
async def embed(ctx: dis.MessageContext):
    await ctx.send(embed=dis.Embed(title="test", description="test", footer="test"))
```

**Expected behaviour**
Send the embed

**Traceback**
```
Traceback (most recent call last):
  File "D:\Dis-Snek\dis_snek\client\client.py", line 1418, in _dispatch_msg_commands
    await self._run_message_command(command, context)
  File "D:\Dis-Snek\dis_snek\client\client.py", line 1289, in _run_message_command
    return await command(ctx)
  File "D:\Dis-Snek\dis_snek\models\snek\command.py", line 102, in __call__
    await self.call_callback(self.callback, context)
  File "D:\Dis-Snek\dis_snek\models\snek\command.py", line 146, in call_callback
    return await callback()
  File "D:\Dis-Snek\bot.py", line 10, in embed
    await ctx.send(embed=dis.Embed(title="test", description="test", footer="test"))
  File "<attrs generated init dis_snek.models.discord.embed.Embed>", line 16, in __init__
    _setattr('footer', __attr_converter_footer(footer))
  File "D:\Dis-Snek\dis_snek\client\utils\converters.py", line 56, in optional_converter
    return converter(val)
  File "D:\Dis-Snek\dis_snek\client\mixins\serialization.py", line 67, in from_dict
    return cls(**cls._filter_kwargs(data, cls._get_init_keys()))
  File "D:\Dis-Snek\dis_snek\client\mixins\serialization.py", line 36, in _filter_kwargs
    return {k: v for k, v in kwargs_dict.items() if k in keys}
AttributeError: 'str' object has no attribute 'items
```

**Comment by Wolfhound905** [comment]
LOL IM SO DUMB
footer has its own class cause of the icon thing XD
I will leave now

**Comment by Wolfhound905** [comment]
Pretend this is spoiler message
||I was gonna say something like this but I was too embarrassed.||
